import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { HomeHeader } from "components/HomeHeader";
import * as ScrollArea from "@radix-ui/react-scroll-area";

export default function Home() {
    return (
        <>
            <Head>
                <title>Next.js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.mainRoot}>
                <div className={styles.home}>
                    <div className={styles.homeFeed}>
                        <HomeHeader />
                        <ScrollArea.Root>
                            <ScrollArea.Viewport>
                            </ScrollArea.Viewport>
                            <ScrollArea.Scrollbar>
                                <ScrollArea.Thumb />
                            </ScrollArea.Scrollbar>
                        </ScrollArea.Root>
                    </div>
                </div>
            </main>
        </>
    );
}
