import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { HomeHeader } from "components/HomeHeader";
import * as ScrollArea from "@radix-ui/react-scroll-area";
import { FeedPosts, PrismaClient, Prisma } from "@prisma/client";
import { GetStaticProps } from "next";
import { Post } from "components/Post";

const PostWithUser = Prisma.validator<Prisma.FeedPostsInclude>()({ user: true });    

export const getStaticProps: GetStaticProps<{ posts: FeedPosts[] }> = async function () {
    const prisma = new PrismaClient();
    const posts = await prisma.feedPosts.findMany({ include: PostWithUser });

    return {
        props: {
            posts: posts,
        }
    }
}

export default function Home({ posts }: { posts: Prisma.FeedPostsGetPayload<{ include: { user: true }}>[]}) {    
    return (
        <>
            <Head>
                <title>Next.js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.mainRoot}>
                <div className={styles.home}>
                    <div className={styles.homeFeed}>
                        <HomeHeader />
                        <ScrollArea.Root>
                            <ScrollArea.Viewport>
                                {posts.map((post) => {
                                    return <Post user={post.user} title={post.postContent}></Post>
                                })}
                            </ScrollArea.Viewport>
                            <ScrollArea.Scrollbar>
                                <ScrollArea.Thumb />
                            </ScrollArea.Scrollbar>
                        </ScrollArea.Root>
                    </div>
                </div>
            </main>
        </>
    );
}
